apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-web-app
  labels:
    app: e-commerce-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-commerce-web-app
  template:
    metadata:
      labels:
        app: e-commerce-web-app
    spec:
      containers:
      - name: web-app-container
        image: your-dockerhub-username/e-commerce-web-app:latest
        ports:
        - containerPort: 80
      

#edit the image and use your real image link
